import turtle

turtle.setup(600,800)
wn = turtle.Screen()
wn.title("flag")
wn.bgcolor("lightyellow")

tess = turtle.Turtle()

tess.pensize(3)
tess.color("black","green")
tess.begin_fill()
tess.forward(160)
tess.left(90)
tess.forward(40)
tess.left(90)
tess.forward(160)
tess.left(90)
tess.forward(40)
tess.end_fill()

tess.penup()
tess.left(180)
tess.forward(40)
tess.right(90)
tess.pendown()

tess.pensize(3)
tess.color("black","white")
tess.begin_fill()

tess.forward(80)
tess.circle(20,360)
tess.penup()
tess.left(90)
tess.forward(20)
tess.right(180)
tess.pendown()
for i in range(10):
    tess.left(36)
    tess.forward(20)
    tess.left(180)
    tess.forward(20)
    tess.left(180)
    
tess.forward(20)
tess.left(90)
tess.forward(80)
tess.left(90)
tess.forward(40)
tess.left(90)
tess.forward(160)
tess.left(90)
tess.forward(40)
tess.end_fill()

tess.penup()
tess.left(180)
tess.forward(40)
tess.right(90)
tess.pendown()

tess.pensize(3)
tess.color("black","orange")
tess.begin_fill()
tess.forward(160)
tess.left(90)
tess.forward(40)
tess.left(90)
tess.forward(160)
tess.left(90)
tess.forward(40)
tess.end_fill()

tess.penup()
tess.forward(80)
tess.pendown()

tess.pensize(4)
tess.forward(300)

tess.left(90)
tess.color("black","brown")
tess.begin_fill()
tess.forward(50)
tess.right(90)
tess.forward(10)

tess.left(90)
tess.forward(30)
tess.right(90)
tess.forward(10)

tess.left(90)
tess.forward(30)
tess.right(90)
tess.forward(10)

tess.right(90)
tess.forward(220)
tess.right(90)
tess.forward(10)

tess.right(90)
tess.forward(30)
tess.left(90)
tess.forward(10)

tess.right(90)
tess.forward(30)
tess.left(90)
tess.forward(10)

tess.right(90)
tess.forward(50)

tess.end_fill()


wn.listen()
turtle.mainloop()
